### ISSUE TITLE
Redlinks

### ISSUE THREAD

**Issue by ktrvs** [ediblewiki/issue-tracking#1]
Redlinks are all over the wiki, members and staff are encouraged to help fix them.

**Comment by Kenny2github** [comment]
FOR HEAVEN'S SAKE REDLINKS ARE NOT A PROBLEM

**Comment by duckboycool** [comment]
Yes they are. They are something that need to be fixed. They aren't a bug, but we do need to fix them, and they are a large issue on the wiki.

**Comment by Kenny2github** [comment]
Red links do **not** need to be fixed. They are healthy to a wiki - they show what is left to create. If there are a lot of red links, that's a good thing, not a bad thing. Please stop treating red links as a problem and start treating them as more of a progress bar instead.

**Comment by duckboycool** [comment]
Your analogy doesn't work if you consider that redlinks are something that we want to fix. Just because they show what is left doesn't mean we keep them. They are something that we _fix_, so this should stay an open issue.

**Comment by duckboycool** [comment]
I am not suggesting that we remove redlinks since I don't want links to be the color red or anything like that. I mean that we create the missing pages as they should be on the wiki. Redlinks can be used to help in the process of fixing missing pages, which is what we are considering redlinks here. We are not trying to remove red links, we are trying to fix them.

**Comment by Kenny2github** [comment]
They are not a problem that need to be fixed or given special attention to. Leave the red links be, and if you have time, create some pages they point to, rather than dedicating time to getting red of them. I'm not suggesting that you're saying make red links blue - I'm saying we shouldn't treat the fact that there are pages left to create as a problem that is worthy of tracking on a fully-fledged *bug*tracker.
