### ISSUE TITLE
EdibleWikiSkin/ScratchWikiSkin2 Pencil Problem

### ISSUE THREAD

**Issue by duckboycool** [ediblewiki/issue-tracking#5]
When using the default ScratchWikiSkin2/EdibleWikiSkin on the wiki, oftentimes the pencil icon which allows to see options about that page just doesn't open. The problem also occurs for the user dropdown menu.

It seems that these issues both occur at the same time, also occur on the Scratch Wiki, and can sometimes be fixed by going to and back from other pages that you viewed in that tab.

So far, the best thing to do when this happens is trying to fix it, or using the URL tools table in the sidebar.

This occurs quite often, and is a large problem.

**Comment by ktrvs** [comment]
@duckboycool For future reference, this could have been opened in the actual skin repo issues. 

This happens because sometimes ResourceLoader doesn't load the JS. It's being tracked in InternationalScratchWiki/ScratchWikiSkin2#10 and when it's fixed, we'll pull it into our version of the skin.

Also, not a large problem as it's fixed when the page fully loads most of the time.

**Comment by duckboycool** [comment]
It happens roughly about half the time for me, but you could keep it closed I suppose.
